### ISSUE TITLE
Plugin is crashing on PHPStorm 5

### ISSUE THREAD

**Issue by barzik** [syllant/idea-plugin-revu#38]
Here are the debug details:

Access is allowed from event dispatch thread only.
Details: Current thread: Thread[ApplicationImpl pooled thread 0,4,Idea Thread Group] 1877349966
Our dispatch thread:Thread[AWT-EventQueue-0 5.0.4#PS-121.390, eap:false,6,Idea Thread Group] 1817824290
SystemEventQueueThread: Thread[AWT-EventQueue-0 5.0.4#PS-121.390, eap:false,6,Idea Thread Group] 1817824290
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:1050)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1034)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.p(FocusManagerImpl.java:1132)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusTransferReady(FocusManagerImpl.java:621)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusBeingTransferred(FocusManagerImpl.java:1086)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:251)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:206)
	at com.intellij.openapi.ui.TextFieldWithBrowseButton.<init>(TextFieldWithBrowseButton.java:47)
	at com.intellij.openapi.ui.TextFieldWithBrowseButton.<init>(TextFieldWithBrowseButton.java:54)
	at com.intellij.ui.RawCommandLineEditor.<init>(RawCommandLineEditor.java:39)
	at com.intellij.ide.util.scopeChooser.ScopeEditorPanel.g(ScopeEditorPanel.java)
	at com.intellij.ide.util.scopeChooser.ScopeEditorPanel.<init>(ScopeEditorPanel.java:77)
	at org.sylfra.idea.plugins.revu.ui.forms.review.FileScopeForm.createUIComponents(FileScopeForm.java:68)
	at org.sylfra.idea.plugins.revu.ui.forms.review.FileScopeForm.$$$setupUI$$$(FileScopeForm.java)
	at org.sylfra.idea.plugins.revu.ui.forms.review.FileScopeForm.<init>(FileScopeForm.java:63)
	at org.sylfra.idea.plugins.revu.ui.forms.review.ReviewForm.createUIComponents(ReviewForm.java:62)
	at org.sylfra.idea.plugins.revu.ui.forms.review.ReviewForm.$$$setupUI$$$(ReviewForm.java)
	at org.sylfra.idea.plugins.revu.ui.forms.review.ReviewForm.<init>(ReviewForm.java:56)
	at org.sylfra.idea.plugins.revu.ui.forms.settings.RevuProjectSettingsForm.createMainForm(RevuProjectSettingsForm.java:314)
	at org.sylfra.idea.plugins.revu.ui.forms.settings.RevuProjectSettingsForm.createMainForm(RevuProjectSettingsForm.java:48)
	at org.sylfra.idea.plugins.revu.ui.forms.AbstractListUpdatableForm.setupUI(AbstractListUpdatableForm.java:55)
	at org.sylfra.idea.plugins.revu.ui.forms.settings.RevuProjectSettingsForm.setupUI(RevuProjectSettingsForm.java:74)
	at org.sylfra.idea.plugins.revu.ui.forms.AbstractListUpdatableForm.<init>(AbstractListUpdatableForm.java:44)
	at org.sylfra.idea.plugins.revu.ui.forms.settings.RevuProjectSettingsForm.<init>(RevuProjectSettingsForm.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
	at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:629)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:242)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:229)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:127)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:347)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:307)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:278)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:331)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$400(ProjectManagerImpl.java:81)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:546)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:542)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$4.run(ProgressManagerImpl.java:259)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:472)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:291)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl$8$1.run(ApplicationImpl.java:684)
	at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

**Comment by syllant** [comment]
Hi,

This version of PHPStorm is too old, I won't spend time on investigating this issue, sorry for that.

Sylvain
