### ISSUE TITLE
Not supported because it's bad for hibernation; use scheduleWithFixedDelay() instead.

### ISSUE THREAD

**Issue by Badazdz** [syllant/idea-plugin-revu#46]
IntelliJ IDEA 16 (IU-145.184.1)
Occured on startup
```
Not supported because it's bad for hibernation; use scheduleWithFixedDelay() instead.
com.intellij.util.IncorrectOperationException: Not supported because it's bad for hibernation; use scheduleWithFixedDelay() instead.
	at com.intellij.util.concurrency.SchedulingWrapper.scheduleAtFixedRate(SchedulingWrapper.java:324)
	at com.intellij.util.concurrency.AppScheduledExecutorService.scheduleAtFixedRate(AppScheduledExecutorService.java:33)
	at org.sylfra.idea.plugins.revu.ui.statusbar.StatusBarComponent.updateState(StatusBarComponent.java:120)
	at org.sylfra.idea.plugins.revu.ui.statusbar.StatusBarComponent.addMessage(StatusBarComponent.java:78)
	at org.sylfra.idea.plugins.revu.ui.statusbar.StatusBarComponent$3.loadFailed(StatusBarComponent.java:180)
	at org.sylfra.idea.plugins.revu.business.ReviewManager.fireReviewLoadFailed(ReviewManager.java:688)
	at org.sylfra.idea.plugins.revu.business.ReviewManager.load(ReviewManager.java:508)
	at org.sylfra.idea.plugins.revu.business.ReviewManager.prepareReviewsToLoad(ReviewManager.java:404)
	at org.sylfra.idea.plugins.revu.business.ReviewManager.loadAndAdd(ReviewManager.java:329)
	at org.sylfra.idea.plugins.revu.business.ReviewManager.access$000(ReviewManager.java:41)
	at org.sylfra.idea.plugins.revu.business.ReviewManager$3.run(ReviewManager.java:173)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:60)
	at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:167)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:161)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:164)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$1000(StartupManagerImpl.java:60)
	at com.intellij.ide.startup.impl.StartupManagerImpl$4.run(StartupManagerImpl.java:198)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:326)
	at com.intellij.openapi.project.DumbServiceImpl.access$1300(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$4.run(DumbServiceImpl.java:304)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.project.DumbServiceImpl.b(DumbServiceImpl.java:302)
	at com.intellij.openapi.project.DumbServiceImpl.access$1100(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$12.run(DumbServiceImpl.java:511)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by syllant** [comment]
Thanks for reporting, fixed in version 2.7.3, just published in JetBrains Plugins Repository
